"""empty message

Revision ID: 0792d0555719
Revises: 54085e69ff0a
Create Date: 2020-09-14 21:59:30.533595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0792d0555719'
down_revision = '54085e69ff0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'borrower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('borrower', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
