"""empty message

Revision ID: 328244c3bfb6
Revises: 3d117e3388bf
Create Date: 2020-09-12 15:03:01.078390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328244c3bfb6'
down_revision = '3d117e3388bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'is_available')
    # ### end Alembic commands ###
