"""empty message

Revision ID: 3d117e3388bf
Revises: 7024c099c41e
Create Date: 2020-09-12 14:59:07.151780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d117e3388bf'
down_revision = '7024c099c41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('zipcode', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['city'])
    op.create_unique_constraint(None, 'user', ['state'])
    op.create_unique_constraint(None, 'user', ['zipcode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
