"""empty message

Revision ID: 4a26c6bfbedd
Revises: 7555e0138099
Create Date: 2020-09-23 00:13:10.187774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a26c6bfbedd'
down_revision = '7555e0138099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_puzzle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_puzzle')
    # ### end Alembic commands ###
