"""empty message

Revision ID: 54085e69ff0a
Revises: d591778088d3
Create Date: 2020-09-11 03:25:05.808977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54085e69ff0a'
down_revision = 'd591778088d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('borrower', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'borrower')
    # ### end Alembic commands ###
