"""empty message

Revision ID: 609337e72004
Revises: a06d56e3f7f4
Create Date: 2020-09-24 22:13:17.645667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609337e72004'
down_revision = 'a06d56e3f7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_box', sa.LargeBinary(), nullable=True))
    op.add_column('puzzle', sa.Column('picture_of_puzzle', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_puzzle')
    op.drop_column('puzzle', 'picture_of_box')
    # ### end Alembic commands ###
