"""empty message

Revision ID: 67876f6ec666
Revises: 8eccb164156b
Create Date: 2020-09-21 20:34:50.038517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67876f6ec666'
down_revision = '8eccb164156b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'puzzle', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puzzle', type_='foreignkey')
    op.drop_column('puzzle', 'owner_id')
    # ### end Alembic commands ###
