"""empty message

Revision ID: 6f8e5efda783
Revises: 8c03f7ddabbf
Create Date: 2020-09-16 13:05:49.228248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f8e5efda783'
down_revision = '8c03f7ddabbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('payment_id', sa.String(length=80), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('payment_id')
    )
    op.alter_column('puzzle', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'puzzle', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puzzle', type_='foreignkey')
    op.alter_column('puzzle', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_table('order')
    # ### end Alembic commands ###
