"""empty message

Revision ID: 7024c099c41e
Revises: 2a69eaee0329
Create Date: 2020-09-12 14:46:35.125171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7024c099c41e'
down_revision = '2a69eaee0329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='user_register')
    op.drop_index('email', table_name='user_register')
    op.drop_index('full_name', table_name='user_register')
    op.drop_index('username', table_name='user_register')
    op.drop_table('user_register')
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['address'])
    op.create_unique_constraint(None, 'user', ['full_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'address')
    op.create_table('user_register',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='user_register_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_register', ['username'], unique=True)
    op.create_index('full_name', 'user_register', ['full_name'], unique=True)
    op.create_index('email', 'user_register', ['email'], unique=True)
    op.create_index('address', 'user_register', ['address'], unique=True)
    # ### end Alembic commands ###
