"""empty message

Revision ID: 7555e0138099
Revises: 67876f6ec666
Create Date: 2020-09-21 20:53:37.626571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7555e0138099'
down_revision = '67876f6ec666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_puzzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_puzzle', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
