"""empty message

Revision ID: 816810467ec6
Revises: a0feb924de30
Create Date: 2020-09-27 22:31:14.492634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816810467ec6'
down_revision = 'a0feb924de30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('zip', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
