"""empty message

Revision ID: 992b043f46f0
Revises: c90754a920fc
Create Date: 2020-09-11 03:15:50.189038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992b043f46f0'
down_revision = 'c90754a920fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('number_of_pieces', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'number_of_pieces')
    # ### end Alembic commands ###
