"""empty message

Revision ID: 9f53550630b8
Revises: 328244c3bfb6
Create Date: 2020-09-13 23:23:10.977561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f53550630b8'
down_revision = '328244c3bfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip_code', sa.Integer(), nullable=False))
    op.drop_index('zipcode', table_name='user')
    op.create_unique_constraint(None, 'user', ['zip_code'])
    op.drop_column('user', 'zipcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zipcode', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('zipcode', 'user', ['zipcode'], unique=True)
    op.drop_column('user', 'zip_code')
    # ### end Alembic commands ###
