"""empty message

Revision ID: a06d56e3f7f4
Revises: 7fce3ab17bb3
Create Date: 2020-09-24 17:56:57.625273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06d56e3f7f4'
down_revision = '7fce3ab17bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_box')
    op.drop_column('puzzle', 'picture_of_puzzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_puzzle', sa.BLOB(), nullable=True))
    op.add_column('puzzle', sa.Column('picture_of_box', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
