"""empty message

Revision ID: a16b19540366
Revises: 9f53550630b8
Create Date: 2020-09-13 23:38:09.489010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16b19540366'
down_revision = '9f53550630b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='user')
    op.drop_index('city', table_name='user')
    op.drop_index('full_name', table_name='user')
    op.drop_index('state', table_name='user')
    op.drop_index('zip_code', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('zip_code', 'user', ['zip_code'], unique=True)
    op.create_index('state', 'user', ['state'], unique=True)
    op.create_index('full_name', 'user', ['full_name'], unique=True)
    op.create_index('city', 'user', ['city'], unique=True)
    op.create_index('address', 'user', ['address'], unique=True)
    # ### end Alembic commands ###
