"""empty message

Revision ID: c43e7015dc53
Revises: d978d6eb403b
Create Date: 2020-09-19 15:09:27.312437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43e7015dc53'
down_revision = 'd978d6eb403b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_box', sa.LargeBinary(), nullable=True))
    op.add_column('puzzle', sa.Column('picture_of_puzzle', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_puzzle')
    op.drop_column('puzzle', 'picture_of_box')
    # ### end Alembic commands ###
