"""empty message

Revision ID: c6bc481646c8
Revises: 816810467ec6
Create Date: 2020-10-02 20:37:12.380112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6bc481646c8'
down_revision = '816810467ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip_code', sa.Integer(), nullable=False))
    op.drop_column('user', 'zip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip', mysql.VARCHAR(length=15), nullable=False))
    op.drop_column('user', 'zip_code')
    # ### end Alembic commands ###
