"""empty message

Revision ID: c90754a920fc
Revises: ddbc17777242
Create Date: 2020-09-11 03:14:27.303902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90754a920fc'
down_revision = 'ddbc17777242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_box', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_box')
    # ### end Alembic commands ###
