"""empty message

Revision ID: d978d6eb403b
Revises: 4ddb6e822578
Create Date: 2020-09-19 15:07:04.059661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd978d6eb403b'
down_revision = '4ddb6e822578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_box')
    op.drop_column('puzzle', 'picture_of_puzzle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_puzzle', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('puzzle', sa.Column('picture_of_box', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
