"""empty message

Revision ID: ddbc17777242
Revises: e6e9e0830b5d
Create Date: 2020-09-11 03:11:36.651635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbc17777242'
down_revision = 'e6e9e0830b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('picture_of_puzzle', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'picture_of_puzzle')
    # ### end Alembic commands ###
